services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: NextGenShop
      POSTGRES_PASSWORD: NextGenShop
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microser-net
    restart: unless-stopped
  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'false'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microser-net
    restart: unless-stopped

  mongdb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: NextGenShop
      MONGO_INITDB_ROOT_PASSWORD: NextGenShop
  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: NextGenShop
      ME_CONFIG_MONGODB_ADMINPASSWORD: NextGenShop
      ME_CONFIG_MONGODB_SERVER: mongo
  mail-dev:
    container_name: ms_maildev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microser-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
